# Generated by Django 3.1.4 on 2020-12-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20201207_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('1', 'F'), ('2', 'D'), ('3', 'C'), ('4', 'B'), ('5', 'A')], max_length=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='num_persons',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('s', 'Small'), ('st', 'Medium'), ('l', 'Large'), ('xl', 'Premium')], max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
