# Generated by Django 2.0.1 on 2020-11-27 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_review_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='booking',
        ),
    ]
