# Generated by Django 3.1.2 on 2020-10-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0002_auto_20201015_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='owners',
            field=models.ManyToManyField(through='project_first_app.Ownership', to='project_first_app.Driver'),
        ),
    ]
