# Generated by Django 3.1.3 on 2020-12-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_agency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ad', 'admin'), ('ma', 'manager'), ('ac', 'accountant')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
