# Generated by Django 3.1.4 on 2020-12-05 15:45

from django.db import migrations, models
import lost.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Кличка')),
                ('age', models.CharField(max_length=20, verbose_name='Возраст')),
                ('gender', models.CharField(choices=[('MALE', 'Мальчик'), ('FEMALE', 'Девочка')], default='MALE', max_length=14, verbose_name='Пол')),
                ('city', models.CharField(max_length=30, verbose_name='Город')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание')),
                ('location', models.CharField(blank=True, max_length=40, null=True, verbose_name='Место')),
                ('contacts', models.CharField(blank=True, max_length=60, null=True, verbose_name='Контакты')),
                ('image', models.ImageField(default='avatar/default.png', upload_to=lost.utils.path_and_rename, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Потерянный питомец',
                'verbose_name_plural': 'Потерянные питомцы',
            },
        ),
    ]
