# Generated by Django 3.1.4 on 2020-12-06 15:01

from django.db import migrations, models
import lost.utils


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0003_auto_20201206_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lost',
            name='image',
            field=models.ImageField(default='lost/default.png', upload_to=lost.utils.path_and_rename, verbose_name='Изображение'),
        ),
    ]
