# Generated by Django 3.1.2 on 2020-10-12 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='possession',
            old_name='date_send',
            new_name='date_end',
        ),
    ]
