# Generated by Django 3.1.4 on 2020-12-08 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arthub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='reviews',
        ),
    ]
