# Generated by Django 3.1.7 on 2021-04-05 16:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210404_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 4, 5, 16, 52, 57, 521445, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
