# Generated by Django 3.1.7 on 2021-04-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_comment_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='city',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='tour',
            new_name='tours',
        ),
        migrations.AddField(
            model_name='reservation',
            name='begin_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='pay',
            field=models.CharField(choices=[('Банковская карта', 'Банковская карта'), ('Наличные деньги', 'Наличные деньги'), ('Веб-сервисы', 'Веб-сервисы')], default='Банковская карта', max_length=25),
        ),
    ]
