# Generated by Django 3.1.2 on 2020-12-16 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_django_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
