# Generated by Django 3.1.1 on 2021-01-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver_license',
            name='number_of_license',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='driver_license',
            name='type',
            field=models.CharField(choices=[('A', 'Moto'), ('B', 'Auto'), ('C', 'Track')], max_length=10),
        ),
        migrations.AlterField(
            model_name='owner',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='owner',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
