# Generated by Django 3.1.1 on 2021-01-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0002_auto_20210117_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
