# Generated by Django 3.1.2 on 2020-10-17 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='possession',
            name='end',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='possession',
            name='start',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
