# Generated by Django 3.1.2 on 2020-10-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0002_auto_20201017_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='nationality',
            field=models.CharField(default='Russian', max_length=30),
        ),
    ]
