# Generated by Django 2.0.1 on 2020-10-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work21', '0002_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='number',
            field=models.IntegerField(),
        ),
    ]
