# Generated by Django 2.0.1 on 2020-10-14 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work21', '0003_auto_20201014_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_start', models.DateField()),
                ('ownership_end', models.DateField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work21.Car')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work21.CarOwner')),
            ],
        ),
        migrations.AddField(
            model_name='carowner',
            name='cars',
            field=models.ManyToManyField(through='work21.Ownership', to='work21.Car'),
        ),
    ]
