# Generated by Django 2.0.1 on 2020-10-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work21', '0004_auto_20201014_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('issued_at', models.DateField()),
                ('license_type', models.CharField(choices=[('A', 'Тип A'), ('B', 'Тип B'), ('C', 'Тип C'), ('D', 'Тип D')], max_length=1)),
            ],
        ),
    ]
