# Generated by Django 2.0.1 on 2020-10-14 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work21', '0005_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='work21.CarOwner'),
            preserve_default=False,
        ),
    ]
