# Generated by Django 2.0.1 on 2020-10-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work21', '0006_license_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='number',
            field=models.CharField(max_length=30),
        ),
    ]
