# Generated by Django 2.0.1 on 2020-10-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work21', '0008_auto_20201027_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carowner',
            name='birth',
            field=models.DateField(null=True),
        ),
    ]
