# Generated by Django 2.0.1 on 2020-10-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work21', '0009_auto_20201027_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carowner',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='carowner',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
