# Generated by Django 3.1.2 on 2020-12-04 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20201204_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='executors',
            field=models.ManyToManyField(related_name='task_executors', through='main.TaskExecutor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TaskInspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.task')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='inspections',
            field=models.ManyToManyField(related_name='task_inspectors', through='main.TaskInspection', to=settings.AUTH_USER_MODEL),
        ),
    ]
