site_name: College
nav:
  - Info: index.md
  - Server:
      - Teacher:
         - "teacher list": teacher/list.md
         - "teacher create": teacher/create.md
         - "teacher delete/update/retrieve": teacher/edit.md

      - Student:
         - "student list": student/list.md
         - "student create": student/create.md
         - "student delete/update/retrieve": student/edit.md

      - Subject:
         - "subject list": subject/list.md
         - "subject create": subject/create.md
         - "subject delete/update/retrieve": subject/edit.md

      - Pair:
         - "pair list": pair/list.md
         - "pair create": pair/create.md
         - "pair delete/update/retrieve": pair/edit.md

      - Mark:
         - "mark list": mark/list.md
         - "mark create": mark/create.md
         - "mark delete/update/retrieve": mark/edit.md

      - Subject To Teacher:
         - "subject to teacher list": subteach/list.md
         - "subject to teacher create": subteach/create.md
         - "subject to teacher delete/update/retrieve": subteach/edit.md
  - Frontend:
      - "sign in": frontend/auth/signin.md
      - "sign up": frontend/auth/signup.md
      - "teacher list": frontend/teacher/list.md
      - "teacher create": frontend/teacher/create.md
      - "teacher delete/update/retrieve": frontend/teacher/edit.md
      - "subject list": frontend/subject/list.md
      - "subject create": frontend/subject/create.md
      - "subject delete/update/retrieve": frontend/subject/edit.md
      - "mark list": frontend/mark/list.md
      - "mark create": frontend/mark/create.md
      - "mark delete/update/retrieve": frontend/mark/edit.md
      - "student list": frontend/student/list.md
      - "student create": frontend/student/create.md
      - "student delete/update/retrieve": frontend/student/edit.md
      - "pair list": frontend/pair/list.md
      - "pair create": frontend/pair/create.md
      - "pair delete/update/retrieve": frontend/pair/edit.md
theme:
 name: material