# Generated by Django 3.1.3 on 2020-11-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels_app', '0003_auto_20201123_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_reserved',
            field=models.BooleanField(default=False, verbose_name='Reservation'),
        ),
    ]
