# Generated by Django 3.1.3 on 2020-12-02 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels_app', '0006_auto_20201201_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestsBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(null=True, verbose_name='StartDate')),
                ('end_date', models.DateTimeField(null=True, verbose_name='EndDate')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Name')),
            ],
        ),
    ]
