# Generated by Django 3.1.3 on 2020-12-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels_app', '0013_auto_20201203_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='start_date',
            field=models.DateTimeField(null=True, verbose_name='StartDate'),
        ),
    ]
