# Generated by Django 3.1.3 on 2020-12-07 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Конференция')),
                ('topic', models.CharField(blank=True, choices=[('Наука', 'Наука'), ('Медицина', 'Медицина'), ('Спорт', 'Спорт')], max_length=10, verbose_name='Тема')),
                ('location', models.CharField(max_length=64, verbose_name='Место')),
                ('start_date', models.DateField(verbose_name='Начало')),
                ('end_date', models.DateField(verbose_name='Окончание')),
                ('description', models.CharField(max_length=512, verbose_name='Описание конференции')),
                ('location_desc', models.CharField(max_length=512, verbose_name='Описание места')),
                ('terms', models.CharField(max_length=256, verbose_name='Условия участия')),
            ],
            options={
                'verbose_name': 'Конференция',
                'verbose_name_plural': 'Конференции',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_type', models.CharField(blank=True, choices=[('Принять участие', 'Принять участие'), ('Опубликовать доклад', 'Опубликовать доклад'), ('Место проведения', 'Место проведения'), ('Другое', 'Другое')], max_length=64, verbose_name='Тип комментария')),
                ('comment_text', models.CharField(max_length=512, verbose_name='Текст комментария')),
                ('comment_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец комментария')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.conference', verbose_name='Конференция')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
