# Generated by Django 3.1.4 on 2021-04-06 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='owner',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
