# Generated by Django 3.1.2 on 2020-10-19 08:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_car_driverlicense_ownership'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='use',
            field=models.ManyToManyField(through='practice.Ownership', to=settings.AUTH_USER_MODEL),
        ),
    ]
