# Generated by Django 3.1.2 on 2020-12-04 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201204_1039'),
        ('accounts', '0002_studentprofile_teacherprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='student_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_class', to='main.studentsclass'),
        ),
    ]
