# Generated by Django 3.1.5 on 2021-01-20 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luch_agency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
