# Generated by Django 3.1.2 on 2020-10-05 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverlicence',
            old_name='artist',
            new_name='driver',
        ),
        migrations.RenameField(
            model_name='ownership',
            old_name='artist',
            new_name='driver',
        ),
        migrations.AddField(
            model_name='ownership',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project_first_app.car'),
            preserve_default=False,
        ),
    ]
