# Generated by Django 3.1.2 on 2020-10-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0002_auto_20201005_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverlicence',
            name='date',
            field=models.DateField(),
        ),
    ]
