# Generated by Django 3.1.2 on 2020-10-10 15:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0004_car_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='car',
            field=models.ForeignKey(default=datetime.date(1970, 1, 1), on_delete=django.db.models.deletion.CASCADE, to='project_first_app.car'),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='driver',
            field=models.ForeignKey(default=datetime.date(1970, 1, 1), on_delete=django.db.models.deletion.CASCADE, to='project_first_app.person'),
        ),
    ]
