# Generated by Django 3.1.2 on 2020-10-10 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0006_auto_20201010_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='owner',
            field=models.ManyToManyField(null=True, through='project_first_app.Ownership', to='project_first_app.Person'),
        ),
        migrations.AlterField(
            model_name='driverlicence',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_first_app.person'),
        ),
    ]
