site_name: Описание сервиса "Warriors"
nav:
    - Home: index.md
    - Tasks: README.md
    - Warriors:
          - "update warrior": warriors/update.md
          - "picking warrior's skills": warriors/skills.md
    - Skills:
          - "skills list": skills/view.md

theme:
    name: material
