# Generated by Django 3.1.6 on 2021-02-19 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('number', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('bus_type', models.IntegerField(choices=[(1000, 'Автозак'), (20, 'Газель')])),
                ('capacity', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('patronymic', models.CharField(max_length=20)),
                ('passport', models.CharField(max_length=10)),
                ('driving_class', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('salary', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('departure_name', models.CharField(max_length=50)),
                ('destination_name', models.CharField(max_length=50)),
                ('departure_time', models.TimeField()),
                ('destination_time', models.TimeField()),
                ('interval_min', models.IntegerField()),
                ('duration_min', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bus_depot.bus')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bus_depot.driver')),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bus_depot.route')),
            ],
        ),
    ]
