# Generated by Django 3.1.2 on 2021-01-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='type',
            field=models.CharField(choices=[('D', 'Bus'), ('A', 'Motorcycle'), ('C', 'Truck'), ('B', 'Car')], default='Choose', max_length=2),
        ),
    ]
