# Generated by Django 3.1.2 on 2021-01-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0002_license_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='type',
            field=models.CharField(choices=[('C', 'Truck'), ('A', 'Motorcycle'), ('D', 'Bus'), ('B', 'Car')], default='Choose', max_length=2),
        ),
    ]
