# Generated by Django 3.1.2 on 2021-01-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0003_auto_20210112_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='type',
            field=models.CharField(choices=[('B', 'Car'), ('A', 'Motorcycle'), ('C', 'Truck'), ('D', 'Bus')], default='Choose', max_length=2),
        ),
    ]
