# Generated by Django 3.1.2 on 2021-01-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0004_auto_20210112_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='type',
            field=models.CharField(choices=[('D', 'Bus'), ('C', 'Truck'), ('B', 'Car'), ('A', 'Motorcycle')], default='Choose', max_length=2),
        ),
    ]
