# Generated by Django 3.1.2 on 2021-01-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0005_auto_20210112_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='type',
            field=models.CharField(choices=[('B', 'Car'), ('D', 'Bus'), ('C', 'Truck'), ('A', 'Motorcycle')], default='Choose', max_length=2),
        ),
    ]
