# Generated by Django 3.1.2 on 2021-01-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0008_auto_20210115_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='type',
            field=models.CharField(choices=[('D', 'Bus'), ('A', 'Motorcycle'), ('B', 'Car'), ('C', 'Truck')], default='Choose', max_length=2),
        ),
    ]
