# Generated by Django 3.1.7 on 2021-04-04 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourfirm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='tour',
            name='payment',
            field=models.CharField(choices=[('полная оплата', 'полная оплата'), ('рассрочка', 'рассрочка')], max_length=13),
        ),
    ]
