# Generated by Django 3.1.4 on 2020-12-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('physical', 'Физическое'), ('meeting', 'Встреча')], default='physical', max_length=14, verbose_name='Категория мерпориятия'),
        ),
    ]
