# Generated by Django 3.1.4 on 2020-12-05 12:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Название')),
                ('description', models.CharField(max_length=40, verbose_name='Описание сбора')),
                ('goal_money', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000000)], verbose_name='Цель сбора')),
                ('current_money', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000000)], verbose_name='Собрано денег')),
                ('donation_times', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100000)], verbose_name='Цель сбора')),
            ],
            options={
                'verbose_name': 'Пожертвование',
                'verbose_name_plural': 'Пожертвования',
            },
        ),
    ]
