# Generated by Django 3.1.4 on 2020-12-05 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0002_charity_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='donation_times',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100000)], verbose_name='Число пожертвований'),
        ),
    ]
