# Generated by Django 3.1.5 on 2021-01-27 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='check_in',
            new_name='is_reserved',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='arrival',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='departure',
        ),
        migrations.RemoveField(
            model_name='review',
            name='arrival',
        ),
        migrations.RemoveField(
            model_name='review',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='review',
            name='departure',
        ),
        migrations.RemoveField(
            model_name='room',
            name='guests',
        ),
        migrations.RemoveField(
            model_name='room',
            name='number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='passport',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telephone',
        ),
        migrations.AddField(
            model_name='booking',
            name='begin_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Begin Date'),
        ),
        migrations.AddField(
            model_name='booking',
            name='end_date',
            field=models.DateField(default=datetime.date.today, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='review',
            name='begin_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата заезда'),
        ),
        migrations.AddField(
            model_name='review',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата добавления'),
        ),
        migrations.AddField(
            model_name='review',
            name='end_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата выезда'),
        ),
        migrations.AddField(
            model_name='review',
            name='text',
            field=models.CharField(max_length=1000, null=True, verbose_name='Текст отзыва'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_num',
            field=models.IntegerField(default=101),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('5', 'все отлично'), ('4', 'могло быть и хуже'), ('3', 'не отлично, но и не ужасно'), ('2', 'могло быть и лучше'), ('1', 'все плохо')], max_length=30, verbose_name='Оцените ваше пребывание в отеле'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('S', 'Standart'), ('C', 'Comfort'), ('L', 'Luxe'), ('S', 'Suite')], max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
