# Generated by Django 3.1.7 on 2021-04-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='contract_number',
            field=models.IntegerField(unique=True),
        ),
    ]
