# Generated by Django 3.1.7 on 2021-04-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210409_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='contract_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
