# Generated by Django 3.1.2 on 2020-10-20 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turism', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='pay',
            field=models.CharField(choices=[('Банковская карта', 'Банковская карта'), ('Наличные деньги', 'Наличные деньги'), ('Веб-сервисы', 'Веб-сервисы')], max_length=25),
        ),
    ]
