# Generated by Django 3.1.4 on 2020-12-07 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplineOfTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_app.discipline', verbose_name='Дисциплина')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(verbose_name='Оценка')),
            ],
        ),
        migrations.CreateModel(
            name='MarkOfStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_app.mark', verbose_name='Оценка')),
            ],
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10, verbose_name='День')),
                ('time', models.CharField(max_length=120, verbose_name='Время')),
                ('group', models.CharField(max_length=120, verbose_name='Группа')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_app.disciplineofteacher', verbose_name='Дисциплина')),
            ],
        ),
        migrations.CreateModel(
            name='PairOfSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_app.pair', verbose_name='Пара')),
            ],
        ),
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_organizer', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=120, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=120, verbose_name='Фамилия')),
                ('room', models.IntegerField(default=0, verbose_name='кабинет')),
                ('discipline', models.ManyToManyField(related_name='teacher_discipline', through='college_app.DisciplineOfTeacher', to='college_app.Discipline', verbose_name='Дисциплина')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=120, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=120, verbose_name='Фамилия')),
                ('group', models.CharField(max_length=120, verbose_name='Группа')),
                ('mark', models.ManyToManyField(related_name='student_mark', through='college_app.MarkOfStudent', to='college_app.Mark', verbose_name='Оценка')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=120, verbose_name='Группа')),
                ('pair', models.ManyToManyField(related_name='schedule_pair', through='college_app.PairOfSchedule', to='college_app.Pair', verbose_name='Пара')),
            ],
        ),
        migrations.AddField(
            model_name='pairofschedule',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_app.schedule', verbose_name='Расписание'),
        ),
        migrations.AddField(
            model_name='markofstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_app.student', verbose_name='Студент'),
        ),
        migrations.AddField(
            model_name='mark',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_app.teacher', verbose_name='Учитель'),
        ),
        migrations.AddField(
            model_name='disciplineofteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_app.teacher', verbose_name='Учитель'),
        ),
    ]
