# Generated by Django 3.1.3 on 2020-11-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_first_app', '0003_auto_20201127_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='passport',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
