# Generated by Django 3.1.3 on 2020-11-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_first_app', '0005_auto_20201127_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='password',
            field=models.CharField(default=12345, max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driver',
            name='username',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
