# Generated by Django 3.1.3 on 2020-12-23 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ad_agency', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chosenservices',
            name='req',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_in_request', to='ad_agency.request', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='request',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_of_user', to='ad_agency.client', verbose_name='Заказчик'),
        ),
    ]
