# Generated by Django 3.1.5 on 2021-01-14 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('passport', models.CharField(max_length=10, unique=True)),
                ('arrival_city', models.CharField(max_length=100)),
                ('check_in', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('3', 'Triple'), ('2', 'Double'), ('1', 'Single')], max_length=1)),
                ('price', models.IntegerField(default=1000)),
                ('floor', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=100)),
                ('telephone', models.CharField(max_length=10, unique=True)),
                ('is_vacant', models.BooleanField(default=True)),
                ('cleaners', models.ManyToManyField(through='hotel_app.CleaningSchedule', to='hotel_app.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='cleaningschedule',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaner', to='hotel_app.room'),
        ),
        migrations.AddField(
            model_name='cleaningschedule',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='hotel_app.employee'),
        ),
        migrations.CreateModel(
            name='BookingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField(blank=True, null=True)),
                ('total_bill', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_details', to='hotel_app.resident')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='hotel_app.room')),
            ],
        ),
    ]
