# Generated by Django 3.1.2 on 2020-10-18 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0002_exhibition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reg', models.DateField()),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_first_app.dog')),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_first_app.exhibition')),
            ],
        ),
        migrations.AddField(
            model_name='exhibition',
            name='member',
            field=models.ManyToManyField(through='project_first_app.Participate', to='project_first_app.Dog'),
        ),
    ]
