# Generated by Django 3.1.2 on 2020-10-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0004_auto_20201019_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='type',
            field=models.CharField(choices=[], max_length=3),
        ),
        migrations.AlterField(
            model_name='owner',
            name='birthday',
            field=models.DateField(),
        ),
    ]
