# Generated by Django 3.1.2 on 2020-10-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0005_auto_20201019_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='type',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=3),
        ),
    ]
