# Generated by Django 3.1.2 on 2020-10-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0006_auto_20201019_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='type',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('M', 'M'), ('A1', 'A1'), ('B1', 'B1'), ('C1', 'C1'), ('D1', 'D1'), ('BE', 'BE'), ('CE', 'CE'), ('DE', 'DE'), ('C1E', 'C1E'), ('D1E', 'D1E')], max_length=3),
        ),
    ]
