# Generated by Django 3.1.2 on 2020-10-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0008_auto_20201019_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
