site_name: Warriors Docs
nav:
 - Home: index.md
 - Skills:
     - "view skills": skills/view_skills.md
 - Warriors:
     - "warriors/warriors professions": warriors/view_warriors_professions.md
     - "warriors/warriors skills": warriors/view_warriors_skills.md
theme:
 name: windmill

