# Generated by Django 3.1.2 on 2021-01-09 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newspapers_distribution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewspapersParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_number', models.IntegerField(default=0, verbose_name='Номер партии')),
                ('amount_of_copies', models.IntegerField(default=0, verbose_name='Количесво экземпляров')),
                ('newspapers_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newspapers_distribution.newspaper', verbose_name='Газета')),
            ],
        ),
    ]
