# Generated by Django 3.1.2 on 2021-01-09 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newspapers_distribution', '0002_newspapersparty'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.IntegerField(default=0, verbose_name='Номер отчёта')),
                ('print_amount', models.IntegerField(default=0, verbose_name='Количесво печатаемых экземпляров')),
                ('office_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newspapers_distribution.postoffice', verbose_name='Отделение')),
                ('party_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newspapers_distribution.newspapersparty', verbose_name='Партия')),
            ],
        ),
    ]
