# Generated by Django 3.1.2 on 2021-01-09 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newspapers_distribution', '0003_distributionreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Print',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('print_amount', models.IntegerField(default=0, verbose_name='Количесво печатаемых экземпляров')),
                ('party_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newspapers_distribution.newspapersparty', verbose_name='Партия')),
                ('printery_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newspapers_distribution.printery', verbose_name='Название типографии')),
            ],
        ),
    ]
