# Generated by Django 3.1.2 on 2021-01-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspapers_distribution', '0005_print_print_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(default='0000-00-00', verbose_name='Дата рождения')),
            ],
        ),
    ]
