# Generated by Django 3.1.2 on 2021-01-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspapers_distribution', '0009_siteuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteuser',
            old_name='address',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='date_of_birth',
            field=models.DateField(default='0000-00-00', verbose_name='Дата рождения'),
        ),
    ]
