# Generated by Django 3.1.2 on 2021-01-15 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspapers_distribution', '0010_auto_20210115_1541'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteUser',
        ),
    ]
