# Generated by Django 3.1.4 on 2021-01-09 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arthub', '0002_remove_user_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
