# Generated by Django 3.1.4 on 2020-12-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='name',
            field=models.CharField(default=None, max_length=40, verbose_name='Кличка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.CharField(max_length=20, verbose_name='Возраст'),
        ),
    ]
