# Generated by Django 3.1.4 on 2020-12-05 15:45

from django.db import migrations, models
import pets.utils


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_auto_20201205_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='image',
            field=models.ImageField(default='avatar/default.png', upload_to=pets.utils.path_and_rename, verbose_name='Изображение'),
        ),
    ]
