export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const INVALID_TOKEN = 'INVALID_TOKEN'
export const REGISTER_USER = 'REGISTER_USER'
export const LOAD_USER = 'LOAD_USER'
export const AUTH_ERROR = 'GET_ERRORS'
export const GET_ERRORS = 'GET_ERRORS'
export const NOT_REGISTER_USER = 'NOT_REGISTER_USER'
