# Generated by Django 3.1.2 on 2020-10-17 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Конференция')),
                ('topic', models.CharField(blank=True, choices=[('Наука', 'Наука'), ('Медицина', 'Медицина'), ('Спорт', 'Спорт')], max_length=10, verbose_name='Тема')),
                ('location', models.CharField(max_length=80, verbose_name='Место проведения')),
                ('start_date', models.DateField(verbose_name='Начало конференции')),
                ('end_date', models.DateField(verbose_name='Окончание конференции')),
                ('description', models.CharField(max_length=500, verbose_name='Описание конференции')),
                ('location_extra', models.CharField(max_length=500, verbose_name='Описание места проведения')),
                ('terms', models.CharField(max_length=300, verbose_name='Условия участия')),
            ],
            options={
                'verbose_name': 'Конференция',
                'verbose_name_plural': 'Конференции',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, choices=[('Принять участие', 'Принять участие'), ('Опубликовать доклад', 'Опубликовать доклад'), ('Место проведения', 'Место проведения'), ('Другое', 'Другое')], max_length=50, verbose_name='Тип комментария')),
                ('text', models.CharField(max_length=300, verbose_name='Текст комментария')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария')),
                ('conference_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.conference', verbose_name='Конференция')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
