# Generated by Django 3.1.2 on 2020-10-17 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='conference_name',
            new_name='conference',
        ),
    ]
