# Generated by Django 3.1.1 on 2020-12-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warriors_app', '0002_auto_20201204_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='warrior',
        ),
        migrations.AlterField(
            model_name='warrior',
            name='skill',
            field=models.ManyToManyField(related_name='skilled_warrior', through='warriors_app.SkillOfWarrior', to='warriors_app.Skill', verbose_name='Умения'),
        ),
    ]
