# Generated by Django 3.1.2 on 2020-11-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlexAir', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='Arrival_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='departure_date',
            field=models.DateTimeField(null=True),
        ),
    ]
