# Generated by Django 3.1.2 on 2021-01-22 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_replica_is_taken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libraryhall',
            name='readers',
        ),
        migrations.AddField(
            model_name='reader',
            name='hall',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='readers', to='main.libraryhall'),
        ),
    ]
