# Generated by Django 3.1.2 on 2021-01-22 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210122_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='hall',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='readers', to='main.libraryhall'),
        ),
    ]
