# Generated by Django 3.1.2 on 2021-01-27 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210122_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookreplica',
            name='is_taken',
        ),
        migrations.AddField(
            model_name='bookreplica',
            name='current_reader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reading_books', to='main.reader'),
        ),
        migrations.AlterField(
            model_name='bookreplica',
            name='library_hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_copies', to='main.libraryhall'),
        ),
    ]
