# Generated by Django 3.1.2 on 2020-10-18 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hw_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='group_number',
            field=models.CharField(choices=[('K33401', 'K33401'), ('K33402', 'K33402'), ('K33421', 'K33421'), ('K33422', 'K33422')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='subject',
            field=models.CharField(choices=[('Web programming', 'Web programming'), ('Web design', 'Web design'), ('Operation systems', 'Operation systems'), ('Front-end', 'Front-end')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='group_number',
            field=models.CharField(choices=[('K33401', 'K33401'), ('K33402', 'K33402'), ('K33421', 'K33421'), ('K33422', 'K33422')], max_length=6, null=True),
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.CharField(choices=[('K33401', 'K33401'), ('K33402', 'K33402'), ('K33421', 'K33421'), ('K33422', 'K33422')], max_length=6, null=True)),
                ('subject', models.CharField(choices=[('Web programming', 'Web programming'), ('Web design', 'Web design'), ('Operation systems', 'Operation systems'), ('Front-end', 'Front-end')], max_length=50, null=True)),
                ('deadline', models.DateField()),
                ('description', models.TextField(max_length=10000)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hw_system.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.TextField(max_length=10000)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hw_system.homework')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hw_system.student')),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=2)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hw_system.homework')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hw_system.student')),
            ],
        ),
    ]
