# Generated by Django 3.1.2 on 2020-10-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='id_number',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
    ]
