# Generated by Django 3.1.2 on 2020-10-13 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='session',
            new_name='owner',
        ),
    ]
