# Generated by Django 3.1.2 on 2020-10-11 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0002_auto_20201011_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownership',
            old_name='date_send',
            new_name='date_end',
        ),
    ]
