# Generated by Django 3.1.2 on 2020-10-11 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0003_auto_20201011_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='date_of_birthday',
            new_name='date_of_birth',
        ),
    ]
