# Generated by Django 3.1.5 on 2021-02-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0002_solution_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='upload',
            field=models.FileField(default='', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
