# Generated by Django 3.1.5 on 2021-01-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='teacher',
            field=models.CharField(max_length=80),
        ),
    ]
