# Generated by Django 3.2 on 2021-04-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('tagline', models.CharField(default='', max_length=100, null=True, verbose_name='Слоган')),
                ('description', models.TextField(max_length=1000, null=True, verbose_name='Описание')),
                ('poster', models.ImageField(null=True, upload_to='movies/', verbose_name='Постер')),
                ('year', models.PositiveSmallIntegerField(default=2022, null=True, verbose_name='Дата выхода')),
                ('country', models.CharField(max_length=30, null=True, verbose_name='Страна')),
                ('directors', models.CharField(max_length=100, null=True, verbose_name='Режиссер')),
                ('actors', models.CharField(max_length=100, null=True, verbose_name='Актеры')),
                ('genres', models.CharField(max_length=100, null=True, verbose_name='Жанры')),
                ('budget', models.PositiveIntegerField(default=0, help_text='указывать сумму в долларах', null=True, verbose_name='Бюджет')),
                ('category', models.CharField(max_length=100, null=True, verbose_name='Категория')),
            ],
        ),
    ]
