# Generated by Django 3.1.3 on 2020-11-25 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels_app', '0004_room_is_reserved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'Reservation', 'verbose_name_plural': 'Reservations'},
        ),
    ]
