# Generated by Django 3.1.3 on 2020-12-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels_app', '0005_auto_20201125_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='end_date',
            field=models.DateField(null=True, verbose_name='EndDate'),
        ),
        migrations.AddField(
            model_name='review',
            name='start_date',
            field=models.DateField(null=True, verbose_name='StartDate'),
        ),
    ]
