# Generated by Django 3.1.3 on 2020-12-03 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels_app', '0010_auto_20201202_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.RemoveField(
            model_name='client',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='client',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='client',
            name='passport',
        ),
    ]
