# Generated by Django 3.1.3 on 2020-12-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels_app', '0012_auto_20201203_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='EndDate'),
        ),
        migrations.DeleteModel(
            name='GuestsBase',
        ),
    ]
