# Generated by Django 3.1.4 on 2021-01-13 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='airlines', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airaport', models.CharField(max_length=30, verbose_name='Аэропорт')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FlexAir.city')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FlexAir.airline', verbose_name='Компания')),
            ],
            options={
                'unique_together': {('company', 'city', 'airaport')},
            },
        ),
    ]
