# Generated by Django 3.1.4 on 2021-01-12 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FlexAir', '0002_airline_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airaport', models.CharField(max_length=30, verbose_name='Аэропорт')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FlexAir.city')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FlexAir.airline', verbose_name='Компания')),
            ],
            options={
                'unique_together': {('company', 'city', 'airaport')},
            },
        ),
    ]
