# Generated by Django 3.1.3 on 2020-11-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_auto_20201114_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='passport',
            field=models.IntegerField(null=True),
        ),
    ]
