site_name: Описание сервиса "Воины"
nav:
 - Home: index.md
 - Endpoints:
     - "Warrior info": endpoints/warrior.md
     - "Warriors and their professions": endpoints/war_prof.md
     - "Warriors and their skills": endpoints/war_skill.md

theme:
 name: material

