# Generated by Django 3.1.2 on 2021-01-15 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspapers_distribution', '0007_auto_20210115_1348'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
